package de.telran.testTryCatch;
//import de.telran.myexeptions.*;
public class Main {
//    public static void main(String[] args) {
//        int a=5;
//        int b=0;
//        try {
//            System.out.println(a/b);
//            //Это не выполниться вообще при ошибке
//        } catch (Exception e) {
//            //System.out.println("b не может быть 0!");
//            //throw new RuntimeException(e);
//            throw new ParamCanNotBeZerro("b не может быть 0!");
//        }
//
//        System.out.println("Готово!");
//    }
}
